"""add phone number

Revision ID: 8bd83257ef15
Revises: 107142ba3a27
Create Date: 2024-01-29 17:26:30.622200

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd83257ef15'
down_revision = '107142ba3a27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
